# Generated by Django 5.1.6 on 2025-02-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('endereco', models.CharField(max_length=1000)),
                ('data_nascimento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
