# Generated by Django 5.1.6 on 2025-02-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pessoas/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='url_portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
